### ISSUE TITLE
Reviewing Solutions After Labs

### ISSUE THREAD

**Issue by Dante8399** [learn-co-curriculum/programming-univbasics-4-array-concept-review-lab#5]
Hi,
I frequently click the 'solutions' button in learn.co (which directs here) to study a solution from someone more seasoned in coding as I sometimes pass a lab by the skin of my teeth. The issue is that the solutions presented, like this one here, seem to either be a completely other language or missing items. Or, it is written in code that is more advanced than what was required to pass the lab itself. Is there a way for these solutions to be available, and in code solely based on what was required to pass it?

Thank you!

**Comment by sgharms** [comment]
@Dante8399 

Looking at our flow of lessons:

![image](https://user-images.githubusercontent.com/50019/60815645-14d8cf00-a166-11e9-8517-7b585a252489.png)

This is the last Array lab, so, unsurprisingly, the one where all the previous ideas are brought together. It's appropriate to feel a bit of a stretch here.

That said, when I look at the `solution` I see:

1. Define a method that accepts parameters (Covered in Programming as Conversation Pt. 3)
2.  Loop through an array* (covered in this module, Pt 4)
3. Test whether two items are equal using an *expression* (covered in Pt 1)
4. Use of explicit `return` to exit a method (Pt 3)
5. Implicit `return`

Now I grant I might well be blinded by the curse of knowledge, but as far as I can tell we've only used pieces we've "put on the board." Can you help me see where the leap is?

**Comment by sgharms** [comment]
@Dante8399 We've not heard back from you in 9 days, so we're going to close this out. Let us know if we missed something but re-opening it! Thanks.
