### ISSUE TITLE
My code is passing but not sure it is the intended method.

### ISSUE THREAD

**Issue by andrew-lewell** [learn-co-curriculum/programming-univbasics-4-array-concept-review-lab#6]
I have been stuck on this for a few hours trying to find a solution that loops over each element in the array with a While loop but then tried this and the following code passes all tests: 

def find_element_index(array, value_to_find)
  array.index(value_to_find)
end

def find_max_value(array)
  sortedArray = array.sort
  
  sortedArray.pop
end

def find_min_value(array)
  sortedArray = array.sort
  
  sortedArray.shift
end

**Comment by sgharms** [comment]
This is not the right path. Not all programming languages have a method built into `Array` that sorts the elements. The goal is for you to be able to write these by hand. When you should leverage built-ins like the above, we'll let you know. 

Coding assignments like these are commonly used as screeners for technical interviews, so we want to make sure you can code this by hand yourself.

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out.

Thanks! 💙
